name: publish
on:
  workflow_run:
    workflows:
    - test
    types:
    - completed
    branches:
    - master
jobs:
  publish:
    name: Publish to Buf Schema Registry
    runs-on: ubuntu-latest
    steps:
    - uses: bufbuild/buf-push-action@v1
      with:
        buf_token: ${{ secrets.BUF_TOKEN }}
