name: style
on:
  pull_request:
jobs:
  branch-naming-style:
    name: Check branch naming style
    runs-on: ubuntu-latest
    steps:
    - uses: deepakputhraya/action-branch-name@master
      with:
        regex: "^[a-zA-Z-]+$"
        ignore: "master"
        min_length: 5
  commit-message-style:
    name: Check commit message style
    runs-on: ubuntu-latest
    steps:
    - uses: mristin/opinionated-commit-message@v3.0.0
      with:
        allow-one-liners: "true"
